import React, { useState } from 'react';
import { TailoredApplication } from '../types';
import { Sparkles, Check, Copy, X, FileText, Briefcase, ArrowRight, ArrowUpRight, Award, ChevronRight } from 'lucide-react';

interface ResumeTailorModalProps {
  application: TailoredApplication | null;
  isLoading: boolean;
  onClose: () => void;
  onViewAllApplications: () => void;
}

export const ResumeTailorModal: React.FC<ResumeTailorModalProps> = ({
  application,
  isLoading,
  onClose,
  onViewAllApplications
}) => {
  const [activeTab, setActiveTab] = useState<'bullets' | 'coverLetter'>('bullets');
  const [copied, setCopied] = useState(false);

  if (!application && !isLoading) return null;

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-slate-900/60 backdrop-blur-xs">
      <div className="relative w-full max-w-4xl bg-white rounded-2xl shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 bg-slate-50/80">
          <div className="flex items-center gap-3">
            <div className="flex items-center justify-center w-10 h-10 rounded-xl bg-indigo-600 text-white font-bold">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-900">
                {isLoading ? 'Antigravity AI is Tailoring Your Application...' : `AI-Tailored Application for ${application?.jobTitle}`}
              </h2>
              <p className="text-xs text-slate-500">
                {isLoading
                  ? 'Optimizing resume bullets for ATS keywords and generating custom cover letter'
                  : `Target Company: ${application?.company} • Generated by Google Gemini AI Engine`}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-slate-600 rounded-lg hover:bg-slate-200/50 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 overflow-y-auto flex-1">
          {isLoading ? (
            <div className="py-16 flex flex-col items-center justify-center text-center">
              <div className="relative mb-6">
                <div className="w-16 h-16 rounded-full border-4 border-indigo-100 border-t-indigo-600 animate-spin" />
                <Sparkles className="w-6 h-6 text-indigo-600 absolute inset-0 m-auto animate-pulse" />
              </div>
              <h3 className="text-lg font-bold text-slate-900 mb-2">
                Analyzing Job Description & Candidate Experience
              </h3>
              <p className="text-sm text-slate-600 max-w-md">
                We are aligning your core technical competencies with ATS requirements, quantifying bullet impacts, and writing a customized cover letter.
              </p>
            </div>
          ) : application ? (
            <div className="space-y-6">
              {/* Match Score Bar */}
              <div className="bg-indigo-50/80 border border-indigo-200/70 rounded-xl p-4 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <div className="flex items-center gap-3">
                  <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-indigo-600 text-white font-bold text-lg shadow-sm">
                    {application.matchScore}%
                  </div>
                  <div>
                    <div className="text-sm font-bold text-indigo-900">
                      ATS & Semantic Fit Score
                    </div>
                    <p className="text-xs text-indigo-700">
                      Optimized specifically for {application.company}&apos;s screening keywords.
                    </p>
                  </div>
                </div>

                <div className="text-xs text-indigo-800 bg-white/80 px-3 py-1.5 rounded-lg border border-indigo-200">
                  <span className="font-semibold">Summary Optimization: </span>
                  {application.tailoredResumeSummary}
                </div>
              </div>

              {/* Tabs */}
              <div className="flex border-b border-slate-200">
                <button
                  onClick={() => setActiveTab('bullets')}
                  className={`flex items-center gap-2 px-4 py-2.5 text-sm font-semibold border-b-2 transition-all ${
                    activeTab === 'bullets'
                      ? 'border-indigo-600 text-indigo-600'
                      : 'border-transparent text-slate-500 hover:text-slate-800'
                  }`}
                >
                  <FileText className="w-4 h-4" />
                  <span>AI-Optimized Resume Bullets ({application.optimizedBullets.length})</span>
                </button>
                <button
                  onClick={() => setActiveTab('coverLetter')}
                  className={`flex items-center gap-2 px-4 py-2.5 text-sm font-semibold border-b-2 transition-all ${
                    activeTab === 'coverLetter'
                      ? 'border-indigo-600 text-indigo-600'
                      : 'border-transparent text-slate-500 hover:text-slate-800'
                  }`}
                >
                  <Briefcase className="w-4 h-4" />
                  <span>Custom Cover Letter</span>
                </button>
              </div>

              {/* Tab 1: Bullets */}
              {activeTab === 'bullets' && (
                <div className="space-y-4">
                  {application.optimizedBullets.map((bullet, idx) => (
                    <div
                      key={idx}
                      className="bg-slate-50 rounded-xl border border-slate-200 p-4 space-y-3"
                    >
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="bg-white p-3.5 rounded-lg border border-slate-200/80">
                          <div className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-1">
                            Original Resume Bullet
                          </div>
                          <p className="text-sm text-slate-600">
                            {bullet.original}
                          </p>
                        </div>

                        <div className="bg-emerald-50/50 p-3.5 rounded-lg border border-emerald-200">
                          {(() => {
                            const cleanText = (bullet.tailored || '')
                              .replace(/\s*\((?:Optimized|incorporated|ATS|Tailored|Aligned|Added|Updated)[^)]*\)\s*$/gi, '')
                              .trim();
                            return (
                              <>
                                <div className="flex items-center justify-between mb-1">
                                  <span className="text-xs font-bold uppercase tracking-wider text-emerald-700">
                                    AI-Tailored Bullet
                                  </span>
                                  <button
                                    onClick={() => handleCopy(cleanText)}
                                    className="text-xs text-emerald-700 hover:underline flex items-center gap-1"
                                  >
                                    <Copy className="w-3 h-3" />
                                    <span>Copy</span>
                                  </button>
                                </div>
                                <p className="text-sm font-semibold text-slate-900">
                                  {cleanText}
                                </p>
                              </>
                            );
                          })()}
                        </div>
                      </div>

                      <div className="flex items-start gap-2 pt-1 border-t border-slate-200/60 text-xs text-slate-600">
                        <Award className="w-4 h-4 text-indigo-600 shrink-0 mt-0.5" />
                        <div>
                          <span className="font-semibold text-slate-800">Why this change works: </span>
                          <span>{bullet.reasoning}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* Tab 2: Cover Letter */}
              {activeTab === 'coverLetter' && (
                <div className="bg-slate-50 rounded-xl border border-slate-200 p-5">
                  <div className="flex items-center justify-between mb-3 pb-3 border-b border-slate-200">
                    <span className="text-xs font-bold uppercase tracking-wider text-slate-500">
                      Personalized Cover Letter for {application.company}
                    </span>
                    <button
                      onClick={() => handleCopy(application.coverLetter)}
                      className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg bg-white border border-slate-300 text-slate-700 hover:bg-slate-50 shadow-2xs"
                    >
                      {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{copied ? 'Copied to Clipboard' : 'Copy Full Text'}</span>
                    </button>
                  </div>
                  <div className="whitespace-pre-wrap text-sm text-slate-700 leading-relaxed font-sans">
                    {application.coverLetter}
                  </div>
                </div>
              )}
            </div>
          ) : null}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-slate-200 bg-slate-50 flex items-center justify-between">
          <span className="text-xs text-slate-500">
            {application ? `Saved to "My Applications" automatically` : ''}
          </span>
          <div className="flex items-center gap-3">
            <button
              onClick={onClose}
              className="px-4 py-2 text-sm font-semibold rounded-xl border border-slate-300 bg-white text-slate-700 hover:bg-slate-50"
            >
              Close
            </button>
            {application && (
              <button
                onClick={() => {
                  onClose();
                  onViewAllApplications();
                }}
                className="flex items-center gap-2 px-4 py-2 text-sm font-semibold rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white shadow-xs"
              >
                <span>View In Pipeline</span>
                <ChevronRight className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
